spring.application.name=ai_notebook

spring.datasource.url=jdbc:mysql://localhost:3306/ai_notebook?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

notion.token=${NOTION_TOKEN:}   # ???? NOTION_TOKEN ??? ??
notion.version=2022-06-28