spring.application.name=ai_notebook

#spring.datasource.url=jdbc:mysql://localhost:3306/ai_notebook?serverTimezone=Asia/Seoul
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

notion.version=2022-06-28
openai.apiKey=${OPENAI_API_KEY}
openai.baseUrl=${OPENAI_BASE_URL:https://api.openai.com/v1}
openai.model=${OPENAI_MODEL:gpt-4o-mini}

#??? ?? ??
app.upload.base=${user.dir}/uploads

#??? ?? ??
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#??? ???
spring.web.resources.static-locations=file:${app.upload.base}/
spring.mvc.static-path-pattern=/uploads/**

#Gemini API ?
gemini.apiKey=${GEMINI_API_KEY}
#gemini.model=gemini-1.5-flash-latest
#gemini.endpoint=https://generativelanguage.googleapis.com/v1beta

gemini.model=gemini-flash-latest
gemini.endpoint=https://generativelanguage.googleapis.com/v1beta
#gemini.endpoint=https://generativelanguage.googleapis.com/v1

#Youtube API ?
youtube.apiKey=${YOUTUBE_API_KEY}
youtube.regionCode=KR
youtube.relevanceLanguage=ko

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG